=== RandalfMx/RandalfConverter/RandalfConverterXls2Xml/xsd/converterXls2Xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.randalf.mx/converterXls2Xml" elementFormDefault="qualified"
    xmlns:xls2xml="http://www.randalf.mx/converterXls2Xml">
    <element name="xls2xml">
        <complexType>
            <sequence>
                <element ref="xls2xml:parameter"/>
                <element maxOccurs="unbounded" ref="xls2xml:input"/>
                <element ref="xls2xml:output"/>
            </sequence>
        </complexType>
    </element>
    <element name="parameter">
        <annotation>
            <documentation xml:lang="it">Lista delle informaziioni per la parametrizzazione dell'applicativo</documentation>
        </annotation>
        <complexType>
            <sequence>
                <element name="pathImageMagick" type="string">
                    <annotation>
                        <documentation xml:lang="it">percorso assoluto in cui Ã¨ stato indtallato il Software ImageMagick</documentation>
                    </annotation>
                </element>
                <element default="10" name="nThread" type="integer">
                    <annotation>
                        <documentation xml:lang="it">Numero massimo di Thread contemporanei lanciati dal programma</documentation>
                    </annotation>
                </element>
                <element default="1000" name="tSleep" type="integer">
                    <annotation>
                        <documentation xml:lang="it">Tempo in milliseconti per la verifica dello stato dei Thread lanciati</documentation>
                    </annotation>
                </element>
                <element default="60000" minOccurs="0" name="tSleepClosed" type="integer">
                    <annotation>
                        <documentation xml:lang="it">Tempo in millisecondi di attesa per la procedura di verifica del termine dell'elaborazione di tutti i thread</documentation>
                    </annotation>
                </element>
            </sequence>
        </complexType>
    </element>
    <element name="input">
        <annotation>
            <documentation xml:lang="it">Lista delle materiale da analizzare in Input</documentation>
        </annotation>
        <complexType>
            <sequence>
                <element name="formatoFile">
                    <complexType>
                        <attribute name="tipo" use="required">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="xls"/>
                                    <enumeration value="csv"/>
                                    <enumeration value="tsv"/>
                                </restriction>
                            </simpleType>
                        </attribute>
                        <attribute default="0" name="primaRiga" type="nonNegativeInteger"
                            use="optional"/>
                    </complexType>
                </element>
                <element ref="xls2xml:path"/>
                <element name="image">
                    <annotation>
                        <documentation xml:lang="it">Indica le informazioni relative alla posizione delle immagini</documentation>
                    </annotation>
                    <complexType>
                        <sequence>
                            <element ref="xls2xml:path"/>
                            <element ref="xls2xml:formatoImg"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
    <element name="output">
        <annotation>
            <documentation xml:lang="it">Lista delle informazioni per la generazione del materiale in output</documentation>
        </annotation>
        <complexType>
            <sequence>
                <element name="typeFileOutput">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="mag"/>
                            <enumeration value="mets"/>
                        </restriction>
                    </simpleType>
                </element>
                <element ref="xls2xml:path"/>
                <element name="cartella" type="integer"/>
                <element name="gen">
                    <complexType>
                        <sequence>
                            <element name="stprog" type="anyURI"/>
                            <element minOccurs="0" name="collection" type="anyURI"/>
                            <element name="agency" type="string"/>
                            <element default="1" name="access_rights">
                                <simpleType>
                                    <restriction base="integer">
                                        <pattern value="0">
                                            <annotation>
                                                <documentation xml:lang="it">uso riservato all'interno dell'istituzione</documentation>
                                            </annotation>
                                        </pattern>
                                        <pattern value="1">
                                            <annotation>
                                                <documentation xml:lang="it">uso pubblico</documentation>
                                            </annotation>
                                        </pattern>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element default="0" name="completeness">
                                <simpleType>
                                    <restriction base="integer">
                                        <pattern value="0">
                                            <annotation>
                                                <documentation xml:lang="it">digitalizzazione completa</documentation>
                                            </annotation>
                                        </pattern>
                                        <pattern value="1">
                                            <annotation>
                                                <documentation xml:lang="it">digitalizzazione parziale</documentation>
                                            </annotation>
                                        </pattern>
                                    </restriction>
                                </simpleType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="bib">
                    <complexType>
                        <sequence>
                            <element name="key">
                                <complexType>
                                    <sequence>
                                        <element maxOccurs="unbounded" ref="xls2xml:dati"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <sequence maxOccurs="unbounded">
                                <element name="campo">
                                    <complexType>
                                        <sequence>
                                            <element ref="xls2xml:dati" maxOccurs="unbounded"/>
                                        </sequence>
                                        <attribute name="tipo" use="required">
                                            <simpleType>
                                                <restriction base="string">
                                                  <enumeration value="bid"/>
                                                  <enumeration value="natura"/>
                                                  <enumeration value="autore"/>
                                                  <enumeration value="titolo"/>
                                                  <enumeration value="pubblicazione"/>
                                                  <enumeration value="biblioteca"/>
                                                  <enumeration value="collocazione"/>
                                                  <enumeration value="inventario"/>
                                                  <enumeration value="annata"/>
                                                  <enumeration value="numero"/>
                                                  <enumeration value="giorno"/>
                                                  <enumeration value="mese"/>
                                                  <enumeration value="anno"/>
                                                  <enumeration value="cronaca"/>
                                                  <enumeration value="year"/>
                                                  <enumeration value="issue"/>
                                                  <enumeration value="stpiece_per"/>
                                                  <enumeration value="part_number"/>
                                                  <enumeration value="part_name"/>
                                                  <enumeration value="stpiece_vol"/>
                                                  <enumeration value="formato"/>
                                                  <enumeration value="descrizione"/>
                                                  <enumeration value="data"/>
                                                  <enumeration value="source"/>
                                                  <enumeration value="relation"/>
                                                  <enumeration value="coverage"/>
                                                </restriction>
                                            </simpleType>
                                        </attribute>
                                    </complexType>
                                </element>
                            </sequence>
                        </sequence>
                    </complexType>
                </element>
                <element name="xml">
                    <complexType>
                        <sequence>
                            <element maxOccurs="unbounded" name="folder">
                                <complexType>
                                    <sequence maxOccurs="unbounded">
                                        <element ref="xls2xml:dati"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="fileName">
                                <complexType>
                                    <sequence maxOccurs="unbounded">
                                        <element ref="xls2xml:dati"/>
                                    </sequence>
                                    <attribute name="extension" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="images">
                    <complexType>
                        <sequence>
                            <element name="nomenclatura">
                                <complexType>
                                    <sequence>
                                        <element maxOccurs="unbounded" ref="xls2xml:dati"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element maxOccurs="unbounded" name="image">
                                <complexType>
                                    <sequence>
                                        <element ref="xls2xml:path"/>
                                        <element ref="xls2xml:formatoImg"/>
                                        <element minOccurs="1" name="usage">
                                            <simpleType>
                                                <restriction base="string">
                                                  <enumeration value="1">
                                                  <annotation>
                                                  <documentation xml:lang="it">Archivio</documentation>
                                                  </annotation>
                                                  </enumeration>
                                                  <enumeration value="2"/>
                                                  <enumeration value="3"/>
                                                  <enumeration value="4"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element minOccurs="0" name="converter">
                                            <complexType>
                                                <sequence>
                                                  <element name="ppi" type="int"/>
                                                  <element default="0" name="width" type="int"/>
                                                  <element default="0" name="height" type="int"/>
                                                  <element default="60" name="quality" type="double"/>
                                                  <element minOccurs="0" name="resize" type="int"/>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <choice>
                    <element name="pagine">
                        <complexType>
                            <sequence>
                                <element name="start" type="integer"/>
                                <element name="stop" type="integer"/>
                            </sequence>
                        </complexType>
                    </element>
                    <element name="pagina" type="integer"/>
                </choice>
                <element minOccurs="0" name="pagInizio" type="integer"/>
            </sequence>
        </complexType>
    </element>
    <element name="path" type="string">
        <annotation>
            <documentation xml:lang="it">Path dell'oggetto
</documentation>
        </annotation>
    </element>
    <element name="formatoImg">
        <annotation>
            <documentation xml:lang="it">Indica il formato dell'immagine</documentation>
        </annotation>
        <complexType>
            <attribute name="formato" use="required">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="tif"/>
                        <enumeration value="jpg"/>
                        <enumeration value="pdf"/>
                    </restriction>
                </simpleType>
            </attribute>
            <attributeGroup ref="xls2xml:gFormat"/>
        </complexType>
    </element>
    <element name="dati">
        <complexType>
            <choice>
                <element name="default" type="string"/>
                <element name="colonna">
                    <complexType>
                        <simpleContent>
                            <extension base="nonNegativeInteger">
                                <attributeGroup ref="xls2xml:gFormat"/>
                            </extension>
                        </simpleContent>
                    </complexType>
                </element>
                <element name="campo">
                    <complexType>
                        <attribute name="tipo" use="required">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="numPagina"/>
                                    <enumeration value="rectoVerso"/>
                                    <enumeration value="numPaginaRomano"/>
                                    <enumeration value="cronaca"/>
                                </restriction>
                            </simpleType>
                        </attribute>
                        <attributeGroup ref="xls2xml:gFormat"/>
                    </complexType>
                </element>
            </choice>
        </complexType>
    </element>
    <attributeGroup name="gFormat">
        <attribute name="decimalFormat" type="string"/>
        <attribute name="converter">
            <simpleType>
                <restriction base="string">
                    <enumeration value="mese">
                        <annotation>
                            <documentation xml:lang="it">Converte il mese dal numero al corrispondente in formato stringa</documentation>
                        </annotation>
                    </enumeration>
                    <enumeration value="romano">
                        <annotation>
                            <documentation xml:lang="it">Converte il testo dal formato Romano in Arabo</documentation>
                        </annotation>
                    </enumeration>
                    <enumeration value="copia"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="prefix" type="string"/>
        <attribute name="suffix" type="string"/>
    </attributeGroup>
</schema>

=== RandalfMx/RandalfConverter/RandalfConverterXls2Xml/xsd/ConfigPiombino.xml
<?xml version="1.0" encoding="UTF-8"?>
<xls2xml:xls2xml xmlns:xls2xml="http://www.randalf.mx/converterXls2Xml"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.randalf.mx/converterXls2Xml converterXls2Xml.xsd ">
  <xls2xml:parameter>
    <xls2xml:pathImageMagick>/opt/local/bin</xls2xml:pathImageMagick>
    <xls2xml:nThread>100</xls2xml:nThread>
    <xls2xml:tSleep>5000</xls2xml:tSleep>
    <xls2xml:tSleepClosed>10000</xls2xml:tSleepClosed>
  </xls2xml:parameter>
  <xls2xml:input>
    <xls2xml:formatoFile tipo="tsv" primaRiga="1"/>
    <xls2xml:path>/Users/massi/temp/Piombino/tsv</xls2xml:path>
    <xls2xml:image>
      <xls2xml:path>/mnt/volume2/Metis/Piombino/La Nazione/Anno 1968</xls2xml:path>
      <xls2xml:formatoImg formato="tif"  decimalFormat="0000"/>
    </xls2xml:image>

  </xls2xml:input>
  <xls2xml:output>
    <xls2xml:typeFileOutput>mag</xls2xml:typeFileOutput>
    <xls2xml:path>/mnt/volume1/Piombino</xls2xml:path>
    <xls2xml:cartella>8</xls2xml:cartella>
    <xls2xml:gen>
      <xls2xml:stprog>http://www.comune.piombino.li.it/pagina666_biblioteche.html</xls2xml:stprog>
      <xls2xml:agency>http://www.comune.piombino.li.it/pagina666_biblioteche.html</xls2xml:agency>
      <xls2xml:access_rights>1</xls2xml:access_rights>
      <xls2xml:completeness>0</xls2xml:completeness>
    </xls2xml:gen>
    <xls2xml:bib>
      <xls2xml:key>
        <xls2xml:dati>
          <xls2xml:colonna>0</xls2xml:colonna>
        </xls2xml:dati>
        <xls2xml:dati>
          <xls2xml:colonna decimalFormat="0000">13</xls2xml:colonna>
        </xls2xml:dati>
        <xls2xml:dati>
          <xls2xml:colonna decimalFormat="00">12</xls2xml:colonna>
        </xls2xml:dati>
        <xls2xml:dati>
          <xls2xml:colonna decimalFormat="00">11</xls2xml:colonna>
        </xls2xml:dati>
      </xls2xml:key>
      <xls2xml:campo tipo="bid">
        <xls2xml:dati>
          <xls2xml:colonna>0</xls2xml:colonna>
        </xls2xml:dati>
      </xls2xml:campo>
      <xls2xml:campo tipo="natura">
        <xls2xml:dati><xls2xml:default>s</xls2xml:default></xls2xml:dati>
      </xls2xml:campo>
      <xls2xml:campo tipo="titolo">
        <xls2xml:dati><xls2xml:default>La nazione</xls2xml:default></xls2xml:dati>
      </xls2xml:campo>
      <xls2xml:campo tipo="pubblicazione">
        <xls2xml:dati><xls2xml:default>[Ed.] Livorno, Portoferraio, Piombino.</xls2xml:default></xls2xml:dati>
      </xls2xml:campo>
      <xls2xml:campo tipo="collocazione">
        <xls2xml:dati><xls2xml:default>Ga.2.165</xls2xml:default></xls2xml:dati>
      </xls2xml:campo>
      <xls2xml:campo tipo="year">
        <xls2xml:dati><xls2xml:colonna>13</xls2xml:colonna></xls2xml:dati>
      </xls2xml:campo>
      <xls2xml:campo tipo="issue">
        <xls2xml:dati><xls2xml:colonna converter="mese" suffix=" ">12</xls2xml:colonna></xls2xml:dati>
        <xls2xml:dati><xls2xml:colonna decimalFormat="00">11</xls2xml:colonna></xls2xml:dati>
      </xls2xml:campo>
      <xls2xml:campo tipo="stpiece_per">
        <xls2xml:dati><xls2xml:default>(</xls2xml:default></xls2xml:dati>
        <xls2xml:dati><xls2xml:colonna decimalFormat="0000">13</xls2xml:colonna></xls2xml:dati>
        <xls2xml:dati><xls2xml:colonna decimalFormat="00">12</xls2xml:colonna></xls2xml:dati>
        <xls2xml:dati><xls2xml:colonna decimalFormat="00">11</xls2xml:colonna></xls2xml:dati>
        <xls2xml:dati><xls2xml:default>)</xls2xml:default></xls2xml:dati>
      </xls2xml:campo>
    </xls2xml:bib>
    <xls2xml:xml>
      <xls2xml:folder>
        <xls2xml:dati>
          <xls2xml:default>La Nazione</xls2xml:default>
        </xls2xml:dati>
      </xls2xml:folder>
      <xls2xml:folder>
        <xls2xml:dati>
          <xls2xml:colonna decimalFormat="0000">13</xls2xml:colonna>
        </xls2xml:dati>
      </xls2xml:folder>
      <xls2xml:folder>
        <xls2xml:dati>
          <xls2xml:colonna decimalFormat="00">12</xls2xml:colonna>
        </xls2xml:dati>
      </xls2xml:folder>
      <xls2xml:fileName extension="xml">
        <xls2xml:dati>
          <xls2xml:colonna decimalFormat="0000">13</xls2xml:colonna>
        </xls2xml:dati>
        <xls2xml:dati>
          <xls2xml:colonna decimalFormat="00">12</xls2xml:colonna>
        </xls2xml:dati>
        <xls2xml:dati>
          <xls2xml:colonna decimalFormat="00">11</xls2xml:colonna>
        </xls2xml:dati>
      </xls2xml:fileName>
    </xls2xml:xml>
    <xls2xml:images>
      <xls2xml:nomenclatura>
        <xls2xml:dati>
          <xls2xml:default>Pagina: </xls2xml:default>
        </xls2xml:dati>
        <xls2xml:dati>
          <xls2xml:campo tipo="numPagina"/>
        </xls2xml:dati>
        <xls2xml:dati>
          <xls2xml:default> </xls2xml:default>
        </xls2xml:dati>
        <xls2xml:dati>
          <xls2xml:campo tipo="cronaca"/>
        </xls2xml:dati>
      </xls2xml:nomenclatura>
      <xls2xml:image>
        <xls2xml:path>Archivio</xls2xml:path>
        <xls2xml:formatoImg formato="tif" decimalFormat="0000"/>
        <xls2xml:usage>1</xls2xml:usage>
      </xls2xml:image>
      <xls2xml:image>
        <xls2xml:path>Internet</xls2xml:path>
        <xls2xml:formatoImg formato="jpg" decimalFormat="0000"/>
        <xls2xml:usage>2</xls2xml:usage>
        <xls2xml:converter>
          <xls2xml:ppi>150</xls2xml:ppi>
          <xls2xml:width>0</xls2xml:width>
          <xls2xml:height>0</xls2xml:height>
          <xls2xml:quality>60</xls2xml:quality>
        </xls2xml:converter>
      </xls2xml:image>
      <xls2xml:image>
        <xls2xml:path>Intranet</xls2xml:path>
        <xls2xml:formatoImg formato="jpg" decimalFormat="0000"/>
        <xls2xml:usage>3</xls2xml:usage>
        <xls2xml:converter>
          <xls2xml:ppi>300</xls2xml:ppi>
          <xls2xml:width>0</xls2xml:width>
          <xls2xml:height>0</xls2xml:height>
          <xls2xml:quality>60</xls2xml:quality>
        </xls2xml:converter>
      </xls2xml:image>
    </xls2xml:images>
    <xls2xml:pagine>
      <xls2xml:start>14</xls2xml:start>
      <xls2xml:stop>15</xls2xml:stop>
    </xls2xml:pagine>
    <xls2xml:pagInizio>17</xls2xml:pagInizio>
  </xls2xml:output>
</xls2xml:xls2xml>
